name: profilescreen
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  slide_to_act: ^2.0.2
  model_viewer_plus:
  shimmer:
  redacted: ^1.0.13
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/svgs/
    - assets/ellipse/Ellipse.svg
    - assets/3d_model/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
